services:
  db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_DB: convergedb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
    volumes:
      - ./data:/var/lib/postgresql/data:z

  app:
    build: .
    container_name: converge-app
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/convergedb
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: 1234